kind: Service
apiVersion: v1
metadata:
  name: web
  labels:
    app: web
    org: planB
spec:
  selector:
    app: web
  ports:
  - name: frontend
    port: 80
  - name: metrics
    port: 9101
    targetPort: 9101